### PR TITLE
Fixed error Encoding format (tmp) is not supported

### PR DESCRIPTION
**Pull request by RenaatoSiilva**
i was using this field in my project and every time i try to save they give me the error

Encoding format (tmp) is not supported

i made a small fix in transformImage adding new parameters :)

### CODE REVIEW

**Comment by stefvanesch** [comment]
@LTKort could you maybe take a look at this?

**Comment by LTKort** [comment]
@RenaatoSiilva Can you add a link for a file you are trying to upload? Because a '.tmp' file is a temporary file and not an official image format.

**Comment by RenaatoSiilva** [comment]
> @RenaatoSiilva Can you add a link for a file you are trying to upload? Because a '.tmp' file is a temporary file and not an official image format.

I think you don't understand... this pull request fix the missing parameter in your package, every file i'll try to upload (bmp, png, jpg) give me error...

**Comment by LTKort** [comment]
@RenaatoSiilva I understand the problem, on which OS, PHP, Nova & Laravel version are you experiencing the issue? And what are you using to process the images ("GD Library" or "Imagick")? 
We need this info and an example file on which it causes the issue, so we can reproduce and fix the issue.

**Comment by RenaatoSiilva** [comment]
OS: Windows 10
PHP: 8.1.7
Image Processor: default with package, i don't changed this
See this video and a picture of me :) 
Laravel Nova Version: v4.11.1 (Silver Surfer)


https://user-images.githubusercontent.com/22757611/191076627-b9a3215e-74f7-4ea1-a182-be70475f76dc.mp4

145106375_1463376084177090_66342596
52047051496_n

**Comment by LTKort** [comment]
@RenaatoSiilva  Could you check if everything works with the newest version (v4.0.2)?

**Comment by RenaatoSiilva** [comment]
> @RenaatoSiilva Could you check if everything works with the newest version (v2.0.2)?

i'm not in my home right now, i'll give a try as soon as possible :)

**Comment by LTKort** [comment]
> @LTKort @stefvanesch it's working now, thanks :) you can close my PR, hope i was helped in some way ...

@RenaatoSiilva  Awesome, glad to help!

**Pull request closed without merging**
